### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by Kaleidoscope39** [MoKee/android_vendor_mk#4]
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: vendor/mokee/build/soong/Android.bp:31:8: module "generated_kernel_includes": cmd: unknown variable '$(PATH_OVERRIDE_SOONG)'

**Comment by albertoduqe** [comment]
Hi there,

Sorry if this inappropriate, my first comment on a github issue... Thing is, I see this is closed but I am having the same error right now trying to build Mokee for lithium...

Any chance somebody could explain how it was fixed??

I can't find any useful information anywhere...

Thanks!

**Comment by VTVishwanath** [comment]
I am building RMX1851 and facing the same issue any luck on this issue? @albertoduqe  or @Kaleidoscope39 ?
